CREATE TABLE company (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    industry VARCHAR(255),
    scale VARCHAR(255),
    contact_person VARCHAR(255),
    phone VARCHAR(255),
    address VARCHAR(512),
    status VARCHAR(64),
    source_excel_row INT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE candidate (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    phone VARCHAR(64),
    email VARCHAR(255),
    resume_text TEXT,
    skills TEXT,
    exp_years INT,
    expected_salary_min DECIMAL(19, 2),
    expected_salary_max DECIMAL(19, 2),
    city VARCHAR(255),
    status VARCHAR(64),
    source VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE job (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL,
    title VARCHAR(512) NOT NULL,
    description TEXT,
    salary_min DECIMAL(19, 2),
    salary_max DECIMAL(19, 2),
    city VARCHAR(255),
    headcount INT,
    urgency VARCHAR(64),
    status VARCHAR(64) NOT NULL DEFAULT 'open',
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_job_company FOREIGN KEY (company_id) REFERENCES company (id)
);

CREATE TABLE recommendation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id BIGINT NOT NULL,
    candidate_id BIGINT NOT NULL,
    match_score DOUBLE PRECISION,
    score_model VARCHAR(255),
    reason TEXT,
    status VARCHAR(50) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_rec_job FOREIGN KEY (job_id) REFERENCES job (id),
    CONSTRAINT fk_rec_candidate FOREIGN KEY (candidate_id) REFERENCES candidate (id),
    CONSTRAINT uq_rec_job_candidate UNIQUE (job_id, candidate_id)
);

CREATE TABLE communication (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recommendation_id BIGINT NOT NULL,
    channel VARCHAR(50) NOT NULL,
    content_summary TEXT,
    next_step VARCHAR(512),
    next_time TIMESTAMP,
    created_by VARCHAR(50) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_comm_rec FOREIGN KEY (recommendation_id) REFERENCES recommendation (id)
);

CREATE TABLE reminder (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recommendation_id BIGINT,
    title VARCHAR(512) NOT NULL,
    remind_at TIMESTAMP NOT NULL,
    channel VARCHAR(255),
    status VARCHAR(64) NOT NULL DEFAULT 'PENDING',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_rem_rec FOREIGN KEY (recommendation_id) REFERENCES recommendation (id)
);

CREATE TABLE idempotency_record (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idempotency_key VARCHAR(512) NOT NULL,
    scope VARCHAR(512) NOT NULL,
    fingerprint VARCHAR(128) NOT NULL DEFAULT '',
    http_status INT NOT NULL,
    response_body TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_idem_key_scope UNIQUE (idempotency_key, scope)
);

CREATE INDEX idx_idem_created ON idempotency_record (created_at);

CREATE TABLE outbound_message (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    delivery_id VARCHAR(64) NOT NULL,
    channel VARCHAR(50) NOT NULL,
    candidate_id BIGINT,
    job_id BIGINT,
    recommendation_id BIGINT,
    template_code VARCHAR(255),
    payload_json TEXT,
    status VARCHAR(64) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_outbound_delivery UNIQUE (delivery_id)
);

CREATE INDEX idx_candidate_email ON candidate (email);
CREATE INDEX idx_job_company ON job (company_id);
